# Generated by Django 3.2.3 on 2021-11-14 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='旧ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='金額')),
                ('date', models.DateField(verbose_name='日付')),
                ('debit_date', models.DateField(verbose_name='引き落とし日')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('card', models.CharField(choices=[('SFC', 'SFC'), ('SFC（家族）', 'SFC（家族）'), ('GoldPoint', 'GoldPoint'), ('ANA USA', 'ANA USA')], max_length=255, verbose_name='カード')),
                ('currency', models.CharField(choices=[('JPY', 'JPY'), ('USD', 'USD')], default='JPY', max_length=3, verbose_name='通貨')),
                ('fee_converted', models.IntegerField(verbose_name='金額（JPY）')),
                ('rate', models.FloatField(blank=True, help_text='JPY for 1 local currency', null=True, verbose_name='レート')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_v2_credit_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_v2_credit_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='旧ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('is_closed', models.BooleanField(default=False, verbose_name='終了フラグ')),
                ('date', models.DateField(verbose_name='日付')),
                ('sum_plan', models.IntegerField(verbose_name='計画総額')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_v2_event_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_v2_event_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='旧ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('way', models.CharField(choices=[('収入', '収入'), ('支出', '支出'), ('振替', '振替'), ('両替', '両替'), ('その他', 'その他')], max_length=255, verbose_name='種別')),
                ('is_shared', models.BooleanField(default=False, verbose_name='共通フラグ')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_v2_usage_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_v2_usage_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='旧ID')),
                ('val', models.IntegerField(verbose_name='値')),
                ('date', models.DateField(verbose_name='日付')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('kind', models.CharField(choices=[('総資産', '総資産'), ('流動資産', '流動資産')], max_length=255, verbose_name='種類')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_v2_target_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_v2_target_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedKakeibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='旧ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='金額')),
                ('date', models.DateField(verbose_name='日付')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_v2_sharedkakeibo_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_v2_sharedkakeibo_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='支払者')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo_v2.usage', verbose_name='用途')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='旧ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('is_investment', models.BooleanField(verbose_name='投資フラグ')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_v2_resource_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_v2_resource_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kakeibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='旧ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='金額')),
                ('date', models.DateField(verbose_name='日付')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('way', models.CharField(choices=[('収入', '収入'), ('支出', '支出'), ('振替', '振替'), ('両替', '両替'), ('その他', 'その他')], max_length=255, verbose_name='種別')),
                ('currency', models.CharField(choices=[('JPY', 'JPY'), ('USD', 'USD')], default='JPY', max_length=3, verbose_name='通貨')),
                ('fee_converted', models.IntegerField(verbose_name='金額（JPY）')),
                ('rate', models.FloatField(blank=True, help_text='JPY for 1 local currency', null=True, verbose_name='レート')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_v2_kakeibo_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo_v2.credit', verbose_name='クレジット')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo_v2.event', verbose_name='イベント')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_v2_kakeibo_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('resource_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_from', to='kakeibo_v2.resource', verbose_name='From')),
                ('resource_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_to', to='kakeibo_v2.resource', verbose_name='To')),
                ('shared', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo_v2.sharedkakeibo', verbose_name='共通家計簿')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo_v2.usage', verbose_name='用途')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='旧ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('method', models.CharField(choices=[('Wire', 'Wire'), ('prestia', 'prestia'), ('その他', 'その他')], max_length=255, verbose_name='Method')),
                ('rate', models.FloatField(blank=True, help_text='JPY for 1 local currency', null=True, verbose_name='レート')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_v2_exchange_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('kakeibo_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_from', to='kakeibo_v2.kakeibo', verbose_name='Kakeibo_From')),
                ('kakeibo_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_to', to='kakeibo_v2.kakeibo', verbose_name='Kakeibo_To')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_v2_exchange_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CronKakeibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='旧ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='金額')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('way', models.CharField(choices=[('収入', '収入'), ('支出', '支出'), ('振替', '振替'), ('両替', '両替'), ('その他', 'その他')], max_length=255, verbose_name='種別')),
                ('is_coping_to_shared', models.BooleanField(verbose_name='共通コピーフラグ')),
                ('kind', models.CharField(choices=[('monthly', '月次'), ('yearly_01', '年次（1月）'), ('yearly_02', '年次（2月）'), ('yearly_03', '年次（3月）'), ('yearly_04', '年次（4月）'), ('yearly_05', '年次（5月）'), ('yearly_06', '年次（6月）'), ('yearly_07', '年次（7月）'), ('yearly_08', '年次（8月）'), ('yearly_09', '年次（9月）'), ('yearly_10', '年次（10月）'), ('yearly_11', '年次（11月）'), ('yearly_12', '年次（12月）')], max_length=255, verbose_name='種類')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_v2_cronkakeibo_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_v2_cronkakeibo_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('resource_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cronkakeibo_resource_from', to='kakeibo_v2.resource', verbose_name='From')),
                ('resource_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cronkakeibo_resource_to', to='kakeibo_v2.resource', verbose_name='To')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo_v2.usage', verbose_name='用途')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='旧ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_v2_creditusage_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_v2_creditusage_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo_v2.usage', verbose_name='用途')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='旧ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('takashi', models.IntegerField(verbose_name='敬士予算')),
                ('hoko', models.IntegerField(verbose_name='朋子予算')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_v2_budget_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_v2_budget_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
