version: '3'
services:
  db2:
    image: postgres:13
    env_file:
    - env/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # db2:
  #   image: gcr.io/cloudsql-docker/gce-proxy:1.16
  #   volumes:
  #     - ~/Documents/Local/gcloud/testiam.json:/config
  #   ports:
  #     - 5432:5432
  #   command: [
  #     "/cloud_sql_proxy",
  #     "-instances=fmanage-202213:asia-northeast1:cloudsql-fk-management=tcp:0.0.0.0:5432",
  #     "-credential_file=/config"
  #   ]

  backend:
    build: .
    command: >
      bash -c '
        python3 manage.py migrate --settings=${SETTINGS} &&
        python3 manage.py collectstatic --no-input  --settings=${SETTINGS} &&
        python3 manage.py runserver 0.0.0.0:8000 --settings=${SETTINGS}'
    ports:
      - 8000
    volumes:
      - .:/home/fk_management
    depends_on:
      - db2

  web:
    image: nginx:1.21
    volumes:
      - .:/etc/nginx/conf.d
      - ./static:/var/www/html/static
    ports:
      - 80:80
    depends_on:
      - backend
  
  selenium:
    image: selenium/standalone-chrome:96.0
    ports:
      - 4444:4444
      - 5900:5900

volumes:
  postgres_data: