version: '3'
services:
  backend:
    build: .
    command: >
      bash -c '
        coverage run manage.py test;
        coverage html;
        coverage xml'
    volumes:
      - .:/home/fk_management
