version: '3'
services:
  db2:
    image: gcr.io/cloudsql-docker/gce-proxy:1.16
    restart: always
    volumes:
      - ~/Documents/Local/gcloud/testiam.json:/config
    ports:
      - 5432
    command: [
      "/cloud_sql_proxy",
      "-instances=fmanage-202213:asia-northeast1:cloudsql-fk-management=tcp:0.0.0.0:5432",
    ]
  backend:
    build: .
    restart: always
    command: >
      bash -c '
        python3 manage.py migrate --settings=${SETTINGS} &&
        python3 manage.py collectstatic --no-input  --settings=${SETTINGS} &&
        gunicorn fk_management.wsgi:application -b 0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE=${SETTINGS}'
    # command: [
    #   "gunicorn", "fk_management.wsgi:application", "-b", "0.0.0.0:8000", 
    #   "--env", "DJANGO_SETTINGS_MODULE=fk_management.environment.develop"
    # ]
    ports:
      - 8000
    volumes:
      - .:/home/fk_management
    depends_on:
      - db2

  web:
    image: nginx:1.21
    restart: always
    volumes:
      - .:/etc/nginx/conf.d
      - ./static:/var/www/html/static
    ports:
      - 8090:80
    depends_on:
      - backend
