version: '3'
services:
  backend_test:
    build: .
    command: >
      bash -c '
        coverage run manage.py test -v3 &> tmp;
        coverage html;
        coverage xml;
        cat tmp;'
    volumes:
      - .:/home/fk_management
