apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-sync-kakeibo
  namespace: fk-management
spec:
  schedule: "30 */1 * * *"
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          shareProcessNamespace: true
          volumes:
          - name: envfile
            secret:
              secretName: secret-test
          containers:
          - name: fk-management-get-kakeibo
            image: tfuruya/fk_management:_VERSION  # to be replaced by Jenkins
            imagePullPolicy: Always
            command: 
              - python3
            args: ["manage.py", "get_kakeibo", "--settings=fk_management.environment.develop"]
            volumeMounts:
              - name: envfile
                mountPath: "/home/fk_management/env"
                readOnly: true
            resources:
              limits:
                memory: 256Mi
                cpu: "0.2"
              requests:
                memory: 32Mi
                cpu: "0.1"