apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
  namespace: fk-management
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      shareProcessNamespace: true
      volumes:
      - name: envfile
        secret:
          secretName: secret-test
      containers:
      - name: fk-management-migrate
        image: tfuruya/fk_management:_VERSION  # to be replaced by Jenkins
        imagePullPolicy: Always
        command: ["python3"]
        args: ["manage.py", "migrate", "--settings=fk_management.environment.develop"]
        volumeMounts:
          - name: envfile
            mountPath: "/home/fk_management/env"
            readOnly: true
        resources:
          limits:
            memory: 256Mi
            cpu: "0.2"
          requests:
            memory: 32Mi
            cpu: "0.1"