# Generated by Django 3.2.3 on 2021-10-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20210829_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('01.BeforeEntry', '01.BeforeEntry'), ('11.Open', '11.Open'), ('21.CloseWon', '21.CloseWon'), ('22.CloseLost', '22.CloseLost'), ('91.Others', '91.Others')], default='01.BeforeEntry', max_length=255, verbose_name='ステータス'),
        ),
    ]
