# Generated by Django 3.2.3 on 2021-05-27 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('fee', models.IntegerField(verbose_name='金額')),
                ('date', models.DateField(verbose_name='日付')),
                ('debit_date', models.DateField(verbose_name='引き落とし日')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('memo', models.CharField(max_length=255, verbose_name='備考')),
                ('card', models.CharField(choices=[('SFC', 'SFC'), ('GoldPoint', 'GoldPoint'), ('SFC（家族）', 'SFC（家族）')], max_length=255, verbose_name='カード')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_credit_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_credit_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('memo', models.CharField(max_length=255, verbose_name='備考')),
                ('is_closed', models.BooleanField(default=False, verbose_name='修了フラグ')),
                ('date', models.DateField(verbose_name='日付')),
                ('sum_plan', models.IntegerField(verbose_name='計画総額')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_event_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_event_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('memo', models.CharField(max_length=255, verbose_name='備考')),
                ('is_investment', models.BooleanField(verbose_name='投資フラグ')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_resource_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_resource_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('memo', models.CharField(max_length=255, verbose_name='備考')),
                ('is_expense', models.BooleanField(verbose_name='支出フラグ')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_way_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_way_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('resource_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_from', to='kakeibo.resource', verbose_name='From')),
                ('resource_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_to', to='kakeibo.resource', verbose_name='From')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('memo', models.CharField(max_length=255, verbose_name='備考')),
                ('is_expense', models.BooleanField(verbose_name='支出フラグ')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_usage_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_usage_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('val', models.IntegerField(verbose_name='値')),
                ('date', models.DateField(verbose_name='日付')),
                ('memo', models.CharField(max_length=255, verbose_name='備考')),
                ('kind', models.CharField(choices=[('総資産', '総資産')], max_length=255, verbose_name='種類')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_target_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_target_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedKakeibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('fee', models.IntegerField(verbose_name='金額')),
                ('date', models.DateField(verbose_name='日付')),
                ('memo', models.CharField(max_length=255, verbose_name='備考')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_sharedkakeibo_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_sharedkakeibo_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='支払者')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo.usage', verbose_name='用途')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kakeibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('fee', models.IntegerField(verbose_name='金額')),
                ('date', models.DateField(verbose_name='日付')),
                ('memo', models.CharField(max_length=255, verbose_name='備考')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_kakeibo_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.credit', verbose_name='クレジット')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.event', verbose_name='イベント')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_kakeibo_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('shared', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.sharedkakeibo', verbose_name='共通家計簿')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo.usage', verbose_name='用途')),
                ('way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo.way', verbose_name='種別')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CronKakeibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('fee', models.IntegerField(verbose_name='金額')),
                ('memo', models.CharField(max_length=255, verbose_name='備考')),
                ('is_coping_to_shared', models.BooleanField(verbose_name='共通コピーフラグ')),
                ('kind', models.CharField(choices=[('monthly', '月次'), ('yearly_01', '年次（1月）'), ('yearly_02', '年次（2月）'), ('yearly_03', '年次（3月）'), ('yearly_04', '年次（4月）'), ('yearly_05', '年次（5月）'), ('yearly_06', '年次（6月）'), ('yearly_07', '年次（7月）'), ('yearly_08', '年次（8月）'), ('yearly_09', '年次（9月）'), ('yearly_10', '年次（10月）'), ('yearly_11', '年次（11月）'), ('yearly_12', '年次（12月）')], max_length=255, verbose_name='種類')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_cronkakeibo_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_cronkakeibo_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo.usage', verbose_name='用途')),
                ('way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo.way', verbose_name='種別')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
