# Generated by Django 3.2.3 on 2021-07-04 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='currency',
            field=models.CharField(choices=[('YEN', 'YEN'), ('USD', 'USD')], default='YEN', max_length=3, verbose_name='通貨'),
        ),
        migrations.AddField(
            model_name='credit',
            name='fee_converted',
            field=models.IntegerField(blank=True, null=True, verbose_name='金額（換算後）'),
        ),
        migrations.AddField(
            model_name='credit',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='レート'),
        ),
        migrations.AddField(
            model_name='cronkakeibo',
            name='resource_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cronkakeibo_resource_from', to='kakeibo.resource', verbose_name='From'),
        ),
        migrations.AddField(
            model_name='cronkakeibo',
            name='resource_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cronkakeibo_resource_to', to='kakeibo.resource', verbose_name='To'),
        ),
        migrations.AddField(
            model_name='kakeibo',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='レート'),
        ),
        migrations.AlterField(
            model_name='cronkakeibo',
            name='way',
            field=models.CharField(choices=[('振替', '振替'), ('支出（現金）', '支出（現金）'), ('支出（カード）', '支出（カード）'), ('収入', '収入'), ('その他', 'その他')], max_length=255, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='kakeibo',
            name='way',
            field=models.CharField(choices=[('振替', '振替'), ('支出（現金）', '支出（現金）'), ('支出（カード）', '支出（カード）'), ('収入', '収入'), ('その他', 'その他')], max_length=255, verbose_name='種別'),
        ),
    ]
