# Generated by Django 3.2.3 on 2021-05-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='共通フラグ'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='is_expense',
            field=models.BooleanField(default=True, verbose_name='支出フラグ'),
        ),
        migrations.AlterField(
            model_name='way',
            name='is_expense',
            field=models.BooleanField(default=True, verbose_name='支出フラグ'),
        ),
    ]
