# Generated by Django 3.2.3 on 2021-07-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_auto_20210704_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='旧ID'),
        ),
        migrations.AddField(
            model_name='credit',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='旧ID'),
        ),
        migrations.AddField(
            model_name='cronkakeibo',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='旧ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='旧ID'),
        ),
        migrations.AddField(
            model_name='kakeibo',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='旧ID'),
        ),
        migrations.AddField(
            model_name='resource',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='旧ID'),
        ),
        migrations.AddField(
            model_name='sharedkakeibo',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='旧ID'),
        ),
        migrations.AddField(
            model_name='target',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='旧ID'),
        ),
        migrations.AddField(
            model_name='usage',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='旧ID'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='currency',
            field=models.CharField(choices=[('JPY', 'JPY'), ('USD', 'USD')], default='YEN', max_length=3, verbose_name='通貨'),
        ),
        migrations.AlterField(
            model_name='kakeibo',
            name='currency',
            field=models.CharField(choices=[('JPY', 'JPY'), ('USD', 'USD')], default='JPY', max_length=3, verbose_name='通貨'),
        ),
    ]
