# Generated by Django 3.2.3 on 2021-07-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_auto_20210704_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='詳細'),
        ),
    ]
