# Generated by Django 3.2.3 on 2021-06-06 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_auto_20210603_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='resource_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_to', to='kakeibo.resource', verbose_name='To'),
        ),
    ]
