# Generated by Django 3.2.3 on 2021-06-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0004_alter_way_resource_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='way',
            old_name='resource_form',
            new_name='resource_from',
        ),
    ]
