# Generated by Django 3.2.3 on 2021-06-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0005_rename_resource_form_way_resource_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='is_transfer',
            field=models.BooleanField(default=True, verbose_name='振替フラグ'),
        ),
    ]
