# Generated by Django 3.2.3 on 2021-08-13 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kakeibo', '0006_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='旧ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('kind', models.CharField(choices=[('貯金', '貯金'), ('返済', '返済')], max_length=255, verbose_name='種別')),
                ('date_open', models.DateField(verbose_name='開始日')),
                ('date_close', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('val_goal', models.IntegerField(verbose_name='目標金額')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_sharedresource_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_sharedresource_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='exchange',
            name='method',
            field=models.CharField(choices=[('Wire', 'Wire'), ('prestia', 'prestia')], max_length=255, verbose_name='Method'),
        ),
        migrations.CreateModel(
            name='SharedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('legacy_id', models.IntegerField(blank=True, null=True, verbose_name='旧ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('val', models.IntegerField(verbose_name='金額')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_sharedtransaction_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='kakeibo_sharedtransaction_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='支払者')),
                ('shared_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo.sharedresource', verbose_name='共通口座')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
