# Generated by Django 3.2.3 on 2021-11-14 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kakeibo', '0009_alter_kakeibo_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedkakeibo',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_by_v1', to=settings.AUTH_USER_MODEL, verbose_name='支払者'),
        ),
    ]
